//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RentACar.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tenant
    {
        public int Id { get; set; }
        public Nullable<System.DateTime> BuyDate { get; set; }
        public Nullable<System.DateTime> ReturnDate { get; set; }
        public string BuyAdress { get; set; }
        public string ReturnAdress { get; set; }
        public Nullable<decimal> TotalPrice { get; set; }
        public Nullable<int> CarsId { get; set; }
        public Nullable<int> UsersId { get; set; }
        public Nullable<int> DayCount { get; set; }
        public Nullable<bool> IsApprove { get; set; }
    
        public virtual Cars Cars { get; set; }
        public virtual Users Users { get; set; }
    }
}
